Introduce bin/print_ruby_errors
This command will now simulate errors and print them to the console:

```
$ cargo run --bin print_ruby_errors
```

For example:

    $ cargo run --bin print_ruby_errors
    # Printing Ruby errors

    The error data is fabricated and may diverge from main.rs.
    Use this output to adjust and inspect formatting.


    ## Error message for RubyBuildpackError::CannotDetectRakeTasks

    ```

    - Command failed: `bundle exec rake -P --trace`
      - exit status: 1
      - stdout: <empty>
      - stderr:

          rake aborted!
          LoadError: cannot load such file -- does_not_exist
          /workspace/Rakefile:1:in `require'
          /workspace/Rakefile:1:in `<top (required)>'
          /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
          /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
          /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
          /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
          /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
          /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
          /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
          /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
          /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
          /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
          /layers/heroku_ruby/gems/ruby/3.1.0/bin/rake:25:in `load'
          /layers/heroku_ruby/gems/ruby/3.1.0/bin/rake:25:in `<top (required)>'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `load'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:23:in `run'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli.rb:492:in `exec'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli.rb:34:in `dispatch'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli.rb:28:in `start'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/exe/bundle:37:in `block in <top (required)>'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          /layers/heroku_ruby/bundler/gems/bundler-2.4.15/exe/bundle:29:in `<top (required)>'
          /layers/heroku_ruby/gems/bin/bundle:108:in `load'
          /layers/heroku_ruby/gems/bin/bundle:108:in `<main>'

    ! ERROR: Error detecting rake tasks
    !
    ! The Ruby buildpack uses rake task information from your application to guide
    ! build logic. Without this information, the Ruby buildpack cannot continue.
    !
    ! Ensure you can run the following command locally with no errors before attempting another build:
    !
    ! `bundle exec rake -P --trace`
    !
    ! Use the information above to debug further.


    ```

	...