Fix whitespace before error:
```
$ reproapp
$ mkdir -p /tmp/159e7d8c193a71cbd28439aaf8872cea; cd /tmp/159e7d8c193a71cbd28439aaf8872cea
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 13.0.6
Using bundler 2.4.15
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Writing lockfile to /private/tmp/159e7d8c193a71cbd28439aaf8872cea/Gemfile.lock
Initialized empty Git repository in /private/tmp/159e7d8c193a71cbd28439aaf8872cea/.git/
[main (root-commit) 3fc3b5f] first
 2 files changed, 16 insertions(+)
 create mode 100644 Gemfile
 create mode 100644 Gemfile.lock
Creating app... done, ⬢ dry-wildwood-29387
 ▸    Your account password will expire in 2 day(s). Please update it before that date to avoid getting locked out.
https://dry-wildwood-29387-68c9b97fa481.herokuapp.com/ | https://git.heroku.com/dry-wildwood-29387.git
⛄️ 3.1.4 🚀 /tmp/159e7d8c193a71cbd28439aaf8872cea (main)
$ cat Gemfile
source 'https://rubygems.org'
gem 'rake'
⛄️ 3.1.4 🚀 /tmp/159e7d8c193a71cbd28439aaf8872cea (main)
$ echo "require 'does_not_exist'" >> Rakefile
⛄️ 3.1.4 🚀 /tmp/159e7d8c193a71cbd28439aaf8872cea (main)
$ cat Rakefile
require 'does_not_exist'
⛄️ 3.1.4 🚀 /tmp/159e7d8c193a71cbd28439aaf8872cea (main)
$ work
⛄️ 3.1.4 🚀 /Users/rschneeman/Documents/projects/work
$ cd buildpacks/buildpacks-ruby
⛄️ 3.1.4 🚀 /Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby (schneems/sandy-error-feedback)
$ cargo libcnb package &&
docker rmi my-image --force  &&
pack build my-image --buildpack target/buildpack/debug/heroku_ruby --path /tmp/159e7d8c193a71cbd28439aaf8872cea
🔍 Locating buildpacks...
📦 [1/1] Building heroku/ruby
Determining automatic cross-compile settings...
Building binaries (x86_64-unknown-linux-musl)...
    Finished dev [unoptimized] target(s) in 0.50s
Writing buildpack directory...
Successfully wrote buildpack directory: ../../target/buildpack/debug/heroku_ruby (12.66 MiB)
✨ Packaging successfully finished!

💡 To test your buildpack locally with pack, run:
pack build my-image-name \
  --buildpack /Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby/target/buildpack/debug/heroku_ruby \
  --path /path/to/application

/Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby/target/buildpack/debug/heroku_ruby
Error: No such image: my-image
22: Pulling from heroku/builder
Digest: sha256:f96abc7de9404c184b9d6fc2cb7380a8633b148e965a1d743c6cebf27dcb3392
Status: Image is up to date for heroku/builder:22
22-cnb: Pulling from heroku/heroku
Digest: sha256:0c422f13416d589a199e3fbf9fa17c1a75b1a120fc60425cd6a20216c432f026
Status: Image is up to date for heroku/heroku:22-cnb
===> ANALYZING
Image with name "my-image" not found
===> DETECTING
heroku/ruby 2.0.0
===> RESTORING
===> BUILDING

# Heroku Ruby Buildpack

- Ruby version `3.1.3` from `default`
  - Installing ............ (9.671s)
- Bundler version `2.4.15` from `Gemfile.lock`
  - Running `gem install bundler --version 2.4.15` .... (1.779s)
- Bundle install
  - Running `BUNDLE_BIN="/layers/heroku_ruby/gems/bin" BUNDLE_CLEAN="1" BUNDLE_DEPLOYMENT="1" BUNDLE_GEMFILE="/workspace/Gemfile" BUNDLE_PATH="/layers/heroku_ruby/gems" BUNDLE_WITHOUT="development:test" bundle install`

      Fetching gem metadata from https://rubygems.org/.
      Fetching rake 13.0.6
      Installing rake 13.0.6
      Using bundler 2.4.15
      Bundle complete! 1 Gemfile dependency, 2 gems now installed.
      Gems in the groups 'development' and 'test' were not installed.
      Bundled gems are installed into `/layers/heroku_ruby/gems`

  - Done (11.022s)
- Setting default processes(es)
  - Detecting gems
  - Running `bundle list` ... (0.314s)
  - Skipping default web process (no web gems detected: `rails`, `railties`, `rack`
- Rake assets install
  - Rake detected (`rake` gem found, `Rakefile` found at `/workspace/Rakefile`)

! ERROR: Error detecting rake tasks
!
! The Ruby buildpack uses rake task information from your application to guide
! build logic. Without this information, the Ruby buildpack cannot continue.
!
! Try to reproduce the error locally by running the command below.
! Once you've fixed all errors locally, commit the result to git and retry
! your build.
!
! If your build continues to fail, application requirements, such as provisioned add-ons,
! environment variables, or installed system packages may be needed. Use the
! information below to debug further.

Debug information:

Command failed: "bundle exec rake -P --trace"
exit status: 1
stdout: <empty>
stderr: rake aborted!
LoadError: cannot load such file -- does_not_exist
/workspace/Rakefile:1:in `require'
/workspace/Rakefile:1:in `<top (required)>'
/layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
/layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
/layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/layers/heroku_ruby/gems/ruby/3.1.0/bin/rake:25:in `load'
/layers/heroku_ruby/gems/ruby/3.1.0/bin/rake:25:in `<top (required)>'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `load'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:23:in `run'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli.rb:492:in `exec'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli.rb:34:in `dispatch'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli.rb:28:in `start'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/exe/bundle:37:in `block in <top (required)>'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/layers/heroku_ruby/bundler/gems/bundler-2.4.15/exe/bundle:29:in `<top (required)>'
/layers/heroku_ruby/gems/bin/bundle:108:in `load'
/layers/heroku_ruby/gems/bin/bundle:108:in `<main>'

ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

It would be nice to format the debug info in a consistent way. Here's a proposal:

```
- Debug information:
  - Command failed: `bundle exec rake -P --trace`
  - exit status: 1
  - stdout: <empty>
  - stderr:

    rake aborted!
    LoadError: cannot load such file -- does_not_exist
    /workspace/Rakefile:1:in `require'
    /workspace/Rakefile:1:in `<top (required)>'
    /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
    /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
    /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
    /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
    /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
    /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
    /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
    /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
    /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
    /layers/heroku_ruby/gems/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
    /layers/heroku_ruby/gems/ruby/3.1.0/bin/rake:25:in `load'
    /layers/heroku_ruby/gems/ruby/3.1.0/bin/rake:25:in `<top (required)>'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `load'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `kernel_load'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:23:in `run'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli.rb:492:in `exec'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli.rb:34:in `dispatch'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/cli.rb:28:in `start'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/exe/bundle:37:in `block in <top (required)>'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
    /layers/heroku_ruby/bundler/gems/bundler-2.4.15/exe/bundle:29:in `<top (required)>'
    /layers/heroku_ruby/gems/bin/bundle:108:in `load'
    /layers/heroku_ruby/gems/bin/bundle:108:in `<main>'

ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

However this is tricky as I don't want to directly couple `fun_run` with the details of `build_output`. Technically `build_output` could be generalized into a reusable crate. I've thought about calling it "bullet_progress" at it displays progress using bullet and markdown formatting. It could be re-used in anything that needs to stream progress that runs sub commands.