Fix clippy for Rust 1.89 (#449)
* Fix clippy for Rust 1.89

```
 error: item in documentation is missing backticks
 --> commons/src/layer/fixtures/metadata_migration_example.md:1:11
  |
1 |  ## Setup DiffMigrateLayer for new layer Metadata
  |           ^^^^^^^^^^^^^^^^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
  = note: `-D clippy::doc-markdown` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(clippy::doc_markdown)]`
help: try
  |
1 -  ## Setup DiffMigrateLayer for new layer Metadata
1 +  ## Setup `DiffMigrateLayer` for new layer Metadata
  |

    Checking libcnb-test v0.29.0
error: item in documentation is missing backticks
   --> commons/src/layer/fixtures/metadata_migration_example.md:108:13
    |
108 |   - Takes a bullet_stream printer for maximal printing consistency
    |             ^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown
help: try
    |
108 -   - Takes a bullet_stream printer for maximal printing consistency
108 +   - Takes a `bullet_stream` printer for maximal printing consistency
    |

error: could not compile `commons` (lib) due to 2 previous errors
```

```
warning: infallible TryFrom impl; consider implementing From, instead
   --> buildpacks/ruby/src/layers/bundle_install_layer.rs:145:1
    |
145 | impl TryFrom<MetadataV3> for MetadataV4 {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
146 |     type Error = std::convert::Infallible;
    |                  ------------------------ infallible error type
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#infallible_try_from
    = note: `#[warn(clippy::infallible_try_from)]` on by default
```

Close #448

* Fix integration tests to read stdout

CNB builder images v0.20.13 (https://github.com/heroku/cnb-builder-images/pull/784) includes the fix for the interleaved buildpack stdout/stderr (https://github.com/buildpacks/lifecycle/pull/1525), however, that will mean some CNB integration tests that test context.pack_stdout and context.pack_stderr will need updating.

The fix is to use stdout instead of stderr as lifecycle is now redirecting the output.