Update default bundler and ruby versions (#374)
* Update default bundler and ruby versions

Rails 8.0.1 needs Ruby 3.2+ and unfortunately they decided to stop shipping with a Ruby version in the Gemfile. I don't yet have `.ruby-version` support, but this will at least allow a `rails new` app to work on Heroku with the default versions.

* Disable metadata migration test

We're no longer modifying metadata, we can safely disable this test (which now fails because the defaults are changing between the versions).

* Update jruby version for integration test

Older versions of JRuby do not play well with newer versions of bundler:

```
  - Running `BUNDLE_BIN="/layers/heroku_ruby/gems/bin" BUNDLE_CLEAN="1" BUNDLE_DEPLOYMENT="1" BUNDLE_GEMFILE="/workspace/Gemfile" BUNDLE_PATH="/layers/heroku_ruby/gems" BUNDLE_WITHOUT="development:test" bundle install`

      Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
      NoMethodError: undefined method `request' for nil:NilClass
      Did you mean?  require
        conflicting_dependencies at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/resolver/conflict.rb:47
        conflicting_dependencies at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/exceptions.rb:32
                      initialize at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/exceptions.rb:26
                             new at org/jruby/RubyClass.java:909
                       exception at org/jruby/RubyException.java:129
                         resolve at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/resolver.rb:193
                         resolve at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/request_set.rb:411
                 resolve_current at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/request_set.rb:423
                  finish_resolve at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems.rb:240
               activate_bin_path at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems.rb:300
                     synchronize at org/jruby/ext/thread/Mutex.java:171
               activate_bin_path at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems.rb:298
                          <main> at /layers/heroku_ruby/bundler/bin/bundle:23
```