Attempting workaround with exec.d
Since exec.d will run any program given to it I want to intentionally leak a bash process that will continue to run in the background. It works locally:

```
$ cat lol.sh
#!/usr/bin/env bash

echo "spawning agentmon" &

while true; do echo "pretend agentmon"; sleep 2; done &
⛄️ 3.1.4 🚀 /tmp
$ ./lol.sh
spawning agentmon
pretend agentmon
⛄️ 3.1.4 🚀 /tmp
$ echo "pretend agentmon
it works"
it works
⛄️ 3.1.4 🚀 /tmp
$ pretend agentmon
echo "lpretend agentmon
ol"
lol
⛄️ 3.1.4 🚀 /tmp
$ pretend agentmon
pretend agentmon
epretend agentmon
echo "pretend agentmon
It keeps runnipretend agentmon
ng even apretend agentmon
s I can pretend agentmon
use the systpretend agentmon
em"
It keeps running even as I can use the system
⛄️ 3.1.4 🚀 /tmp
$ pretend agentmon
```

However when I try to replicate this with exec.d it never seems to end the `exec.d` program and never yields control to a different process:

```
$ cargo libcnb package; docker rmi my-image; pack build  my-image --buildpack /Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby/target/buildpack/debug/heroku_statsd-metrics  --path /tmp/47b6249d5e0a353f91910f848a700061 --pull-policy never
🔍 Locating buildpacks...
📦 [1/2] Building heroku/ruby
Determining automatic cross-compile settings...
Building binaries (x86_64-unknown-linux-musl)...
    Finished dev [unoptimized] target(s) in 0.89s
Writing buildpack directory...
Successfully wrote buildpack directory: ../../target/buildpack/debug/heroku_ruby (12.64 MiB)
📦 [2/2] Building heroku/statsd-metrics
Determining automatic cross-compile settings...
Building binaries (x86_64-unknown-linux-musl)...
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
    Blocking waiting for file lock on package cache
   Compiling heroku-statsd-metrics v0.0.0 (/Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby/buildpacks/metrics-agent)
warning: unused import: `DownloadAgentmon`
 --> buildpacks/metrics-agent/src/main.rs:3:40
  |
3 | use crate::layers::download_agentmon::{DownloadAgentmon, DownloadAgentmonError};
  |                                        ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `heroku-statsd-metrics` (bin "heroku-statsd-metrics") generated 1 warning (run `cargo fix --bin "heroku-statsd-metrics"` to apply 1 suggestion)
    Finished dev [unoptimized] target(s) in 7.67s
Writing buildpack directory...
Successfully wrote buildpack directory: ../../target/buildpack/debug/heroku_statsd-metrics (6.58 MiB)
✨ Packaging successfully finished!

💡 To test your buildpack locally with pack, run:
pack build my-image-name \
  --buildpack /Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby/target/buildpack/debug/heroku_ruby \
  --buildpack /Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby/target/buildpack/debug/heroku_statsd-metrics \
  --path /path/to/application

/Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby/target/buildpack/debug/heroku_ruby
/Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby/target/buildpack/debug/heroku_statsd-metrics
Error: No such image: my-image
===> ANALYZING
Image with name "my-image" not found
===> DETECTING
heroku/statsd-metrics 2.0.0
===> RESTORING
===> BUILDING

# Heroku Statsd Metrics Agent

- Done
===> EXPORTING
Adding layer 'heroku/statsd-metrics:layer_name'
Adding layer 'buildpacksio/lifecycle:launch.sbom'
Adding 1/1 app layer(s)
Adding layer 'buildpacksio/lifecycle:launcher'
Adding layer 'buildpacksio/lifecycle:config'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
no default process type
Saving my-image...
*** Images (516b6641ecda):
      my-image
Successfully built image my-image
⛄️ 3.1.4 🚀 /Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby (schneems/metrics-agent-download-rebase)
$ docker run -it --rm --entrypoint='/cnb/lifecycle/launcher' my-image 'sleep 60'
spawning agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
^[pretend agentmon
^C%
⛄️ 3.1.4 🚀 /Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby (schneems/metrics-agent-download-rebase)
$ docker run -it --rm --entrypoint='/cnb/lifecycle/launcher' my-image 'bash'
spawning agentmon
pretend agentmon

lol
pretend agentmon
echo lopretend agentmon
l
pretend agentmon
ls
pretend agentmon
cd
echpretend agentmon
o "it never pretend agentmon
ends"
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
pretend agentmon
```

Here's the test directory (needs barnes in the Gemfile.lock to execute)

```
$ ls /tmp/47b6249d5e0a353f91910f848a700061
Gemfile		Gemfile.lock
⛄️ 3.1.4 🚀 /tmp/47b6249d5e0a353f91910f848a700061
$ cat /tmp/47b6249d5e0a353f91910f848a700061/Gemfile
source "https://rubygems.org"

gem "barnes"
⛄️ 3.1.4 🚀 /tmp/47b6249d5e0a353f91910f848a700061
$ cat /tmp/47b6249d5e0a353f91910f848a700061/Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    barnes (0.0.9)
      multi_json (~> 1)
      statsd-ruby (~> 1.1)
    multi_json (1.15.0)
    statsd-ruby (1.5.0)

PLATFORMS
  x86_64-darwin-22

DEPENDENCIES
  barnes

BUNDLED WITH
   2.4.15
```