Update build output
Errors in the middle of an `Installing ... ` section looked weird because it would start rendering on the same line:

```
# Heroku Statsd Metrics Agent

- Metrics agent
  - Installing .! ERROR: Could not install Statsd agent
!
! An error occured while downloading and installing the metrics agent
! the buildpack cannot continue
!

Debug information: Could not untar: failed to iterate over archive
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

I changed it so it's now like this:

```

# Heroku Statsd Metrics Agent

- Metrics agent
  - Downloading ..
! ERROR: Could not install Statsd agent
!
! An error occured while downloading and installing the metrics agent
! the buildpack cannot continue
!
! Debug information:
Could not untar: failed to iterate over archive

ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

I think it would look better to indent the "debug information" at least. Maybe add an extra newline.