Resolve dependency issues from #446 (#450)
* Bump the rust-dependencies group across 1 directory with 7 updates

Bumps the rust-dependencies group with 7 updates in the / directory:

| Package | From | To |
| --- | --- | --- |
| [bullet_stream](https://github.com/schneems/bullet_stream) | `0.10.0` | `0.11.0` |
| [glob](https://github.com/rust-lang/glob) | `0.3.2` | `0.3.3` |
| [libherokubuildpack](https://github.com/heroku/libcnb.rs) | `0.29.0` | `0.29.1` |
| [rand](https://github.com/rust-random/rand) | `0.9.1` | `0.9.2` |
| [thiserror](https://github.com/dtolnay/thiserror) | `2.0.12` | `2.0.14` |
| [toml](https://github.com/toml-rs/toml) | `0.8.23` | `0.9.5` |
| [fancy-regex](https://github.com/fancy-regex/fancy-regex) | `0.14.0` | `0.16.1` |



Updates `bullet_stream` from 0.10.0 to 0.11.0
- [Changelog](https://github.com/heroku-buildpacks/bullet_stream/blob/main/CHANGELOG.md)
- [Commits](https://github.com/schneems/bullet_stream/compare/v0.10.0...v0.11.0)

Updates `glob` from 0.3.2 to 0.3.3
- [Release notes](https://github.com/rust-lang/glob/releases)
- [Changelog](https://github.com/rust-lang/glob/blob/master/CHANGELOG.md)
- [Commits](https://github.com/rust-lang/glob/compare/v0.3.2...v0.3.3)

Updates `libherokubuildpack` from 0.29.0 to 0.29.1
- [Release notes](https://github.com/heroku/libcnb.rs/releases)
- [Changelog](https://github.com/heroku/libcnb.rs/blob/main/CHANGELOG.md)
- [Commits](https://github.com/heroku/libcnb.rs/compare/v0.29.0...v0.29.1)

Updates `rand` from 0.9.1 to 0.9.2
- [Release notes](https://github.com/rust-random/rand/releases)
- [Changelog](https://github.com/rust-random/rand/blob/master/CHANGELOG.md)
- [Commits](https://github.com/rust-random/rand/compare/rand_core-0.9.1...rand_core-0.9.2)

Updates `thiserror` from 2.0.12 to 2.0.14
- [Release notes](https://github.com/dtolnay/thiserror/releases)
- [Commits](https://github.com/dtolnay/thiserror/compare/2.0.12...2.0.14)

Updates `toml` from 0.8.23 to 0.9.5
- [Commits](https://github.com/toml-rs/toml/compare/toml-v0.8.23...toml-v0.9.5)

Updates `fancy-regex` from 0.14.0 to 0.16.1
- [Release notes](https://github.com/fancy-regex/fancy-regex/releases)
- [Changelog](https://github.com/fancy-regex/fancy-regex/blob/main/CHANGELOG.md)
- [Commits](https://github.com/fancy-regex/fancy-regex/compare/0.14.0...0.16.1)

---
updated-dependencies:
- dependency-name: bullet_stream
  dependency-version: 0.11.0
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: rust-dependencies
- dependency-name: glob
  dependency-version: 0.3.3
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: rust-dependencies
- dependency-name: libherokubuildpack
  dependency-version: 0.29.1
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: rust-dependencies
- dependency-name: rand
  dependency-version: 0.9.2
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: rust-dependencies
- dependency-name: thiserror
  dependency-version: 2.0.14
  dependency-type: direct:production
  update-type: version-update:semver-patch
  dependency-group: rust-dependencies
- dependency-name: toml
  dependency-version: 0.9.5
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: rust-dependencies
- dependency-name: fancy-regex
  dependency-version: 0.16.1
  dependency-type: direct:production
  update-type: version-update:semver-minor
  dependency-group: rust-dependencies
...

Signed-off-by: dependabot[bot] <support@github.com>

* Fix timer restarting

```
error[E0599]: no method named `start_timer` found for unit type `()` in the current scope
  --> buildpacks/ruby/src/layers/ruby_install_layer.rs:96:34
   |
96 |                 timer = canceled.start_timer("Retrying");
   |                                  ^^^^^^^^^^^ method not found in `()`
```

* Update libcnb version

* Update magic_migrate

* Fix clippy

```
error: this let-binding has unit value
   --> buildpacks/ruby/src/layers/ruby_install_layer.rs:102:5
    |
102 |     _ = timer.done();
    |     ^^^^^^^^^^^^^^^^ help: omit the `let` binding: `timer.done();`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#let_unit_value
    = note: `-D clippy::let-unit-value` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::let_unit_value)]`

error: matching over `()` is more explicit
   --> buildpacks/ruby/src/layers/ruby_install_layer.rs:102:5
    |
102 |     _ = timer.done();
    |     ^ help: use `()` instead of `_`: `()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ignored_unit_patterns
    = note: `-D clippy::ignored-unit-patterns` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::ignored_unit_patterns)]`

error: could not compile `heroku-ruby-buildpack` (bin "heroku-ruby-buildpack") due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `heroku-ruby-buildpack` (bin "heroku-ruby-buildpack" test) due to 2 previous errors
```

* Prefer From over TryFrom with infallible error

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>