Provide Ruby always, request Node w/ package.json
By providing and never failing other build packs can invoke Ruby without a Gemfile. It's not perfect and needs to be refactored into a ruby-engine with a default version, but it's good enough for now.

When there's a package.json we need to install `node.js`. We should be able to do this by `require`-ing `node` from the builder: https://github.com/heroku/buildpacks-nodejs/blob/e1279b5ceae75b686f52512377b71ead6b0819f8/buildpacks/nodejs-engine/src/main.rs#L39. However it's failing:

https://heroku.slack.com/archives/C02GZCPPV38/p1664917346552659


You can reproduce the failure with:

```
$ cargo test --locked test_getting_started_rails_app -- --ignored
    Finished test [unoptimized + debuginfo] target(s) in 0.56s
     Running unittests src/lib.rs (target/debug/deps/heroku_ruby_buildpack-ce945ecd0089e1e9)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 9 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/heroku_ruby_buildpack-228b72424a2355b9)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 18 filtered out; finished in 0.00s

     Running tests/integration_test.rs (target/debug/deps/integration_test-43908ad64c0efd70)

running 1 test
    Finished dev [unoptimized] target(s) in 0.28s
test test_getting_started_rails_app ... FAILED

failures:

---- test_getting_started_rails_app stdout ----
thread 'test_getting_started_rails_app' panicked at 'pack command unexpectedly failed with exit-code 1!

pack stdout:
Previous image with name "libcnbtest_gvdmocebphgltslwulfjllqypnwtze" not found
===> DETECTING
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating


pack stderr:
ERROR: failed to build: executing lifecycle: failed with status code: 20
', /Users/rschneeman/.cargo/registry/src/github.com-1ecc6299db9ec823/libcnb-test-0.11.0/src/test_runner.rs:172:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_getting_started_rails_app

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 2.43s

error: test failed, to rerun pass '--test integration_test'
```

Or

```
$ cargo libcnb package
$ pack build my-image --builder heroku/builder:22 --buildpack target/buildpack/debug/heroku_ruby --path tests/fixtures/ruby-getting-started
```

Like:

```
$ cargo libcnb package
INFO - Reading buildpack metadata...
INFO - Found buildpack heroku/ruby with version 2.0.0.
INFO - Determining automatic cross-compile settings...
INFO - Building binaries (x86_64-unknown-linux-musl)...
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
INFO - Writing buildpack directory...
INFO - Successfully wrote buildpack directory: target/buildpack/debug/heroku_ruby (122.6M)
INFO - Packaging successfully finished!
INFO - Hint: To test your buildpack locally with pack, run: pack build my-image --buildpack target/buildpack/debug/heroku_ruby --path /path/to/application
⛄️ 3.1.2 🚀 /Users/rschneeman/Documents/projects/work/buildpacks/buildpacks-ruby (schneems/fresh-start-rust)
$ pack build my-image --builder heroku/builder:22 --buildpack target/buildpack/debug/heroku_ruby --path tests/fixtures/ruby-getting-started
22: Pulling from heroku/builder
Digest: sha256:6f26dd335a6ca01949a2184a9192622a17b304cbaa1fe46fed67bcff7815fe06
Status: Image is up to date for heroku/builder:22
22-cnb: Pulling from heroku/heroku
Digest: sha256:3146dcdc04f935b23265879eb765eb5c2ca3bbfcf758dfca2b04121b1b4a793f
Status: Image is up to date for heroku/heroku:22-cnb
0.14.1: Pulling from buildpacksio/lifecycle
Digest: sha256:56019ba74831e3444f33ee8c0201f18cc300213bac353b8b6a79c7a1669b7a49
Status: Image is up to date for buildpacksio/lifecycle:0.14.1
===> ANALYZING
===> DETECTING
[detector] ERROR: No buildpack groups passed detection.
[detector] ERROR: Please check that you are running against the correct path.
[detector] ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 20
```