Remove unused metadata
Weirdly if you just remove the `buildpack.toml` entry it still compiles but detect fails:

```
$ docker image rm my-image --force; cargo libcnb package && pack build my-image --buildpack target/buildpack/debug/heroku_ruby --path /tmp/921074ad660707d1613dd7bb7833cc5b
Error: No such image: my-image
INFO - Reading buildpack metadata...
INFO - Found buildpack heroku/ruby with version 2.0.0.
INFO - Determining automatic cross-compile settings...
INFO - Building binaries (x86_64-unknown-linux-musl)...
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
INFO - Writing buildpack directory...
INFO - Successfully wrote buildpack directory: target/buildpack/debug/heroku_ruby (106.4M)
INFO - Packaging successfully finished!
INFO - Hint: To test your buildpack locally with pack, run: pack build my-image --buildpack target/buildpack/debug/heroku_ruby --path /path/to/application
20: Pulling from heroku/buildpacks
Digest: sha256:e1b3d25cccae5d860a2b3f369c5fdbb5462e75bca074a69e69e3c37a0519cf7a
Status: Image is up to date for heroku/buildpacks:20
20-cnb: Pulling from heroku/heroku
Digest: sha256:e245a61ac1f01b47d66e362f220548e3e8874b7395129adb481ee0f081a265e6
Status: Image is up to date for heroku/heroku:20-cnb
===> ANALYZING
Previous image with name "my-image" not found
===> DETECTING
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 20
```

The problem is the coupling between the file and the stated metadata in `main.rs` but the surprising thing is it doesn't fail to compile or raise a warning or something. Seems like a bug.