Failing warn_later test
Due to the implementation of the announce logging (warning, important) needing whitespace above and below their blocks, calling `announce.warn_later` accidentally introduce whitespace` into the build output.

This test fails:

```
thread 'output::build_log::test::warn_later_doesnt_output_newline' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :

 # Walkin' on the Sun

 - So don't delay, act now, supplies are running out
   - Allow if you're still alive, six to eight years to arrive
   - And if you follow, there may be a tomorrow
>
   - But if the offer's shunned
   - You might as well be walking on the Sun
 - Done (finished in < 0.1s)

 ! And all that glitters is gold

 ! Only shooting stars break the mold

', commons/src/output/build_log.rs:646:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I previously noted that this can also be triggered via calling `.announce().end_announce()` which seemed trivial enough (and unlikely) to avoid. However I'm re-thinking that I want to insert a preliminary guard state between calling `.announce()` and `end_announce()` but it gets gnarly because that intermediate state would carry duplicate associated functions.

An alternative could be to move `warn_later` to individual states (instead of needing to create an Announcement logger).