Update jruby version for integration test
Older versions of JRuby do not play well with newer versions of bundler:

```
  - Running `BUNDLE_BIN="/layers/heroku_ruby/gems/bin" BUNDLE_CLEAN="1" BUNDLE_DEPLOYMENT="1" BUNDLE_GEMFILE="/workspace/Gemfile" BUNDLE_PATH="/layers/heroku_ruby/gems" BUNDLE_WITHOUT="development:test" bundle install`

      Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
      NoMethodError: undefined method `request' for nil:NilClass
      Did you mean?  require
        conflicting_dependencies at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/resolver/conflict.rb:47
        conflicting_dependencies at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/exceptions.rb:32
                      initialize at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/exceptions.rb:26
                             new at org/jruby/RubyClass.java:909
                       exception at org/jruby/RubyException.java:129
                         resolve at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/resolver.rb:193
                         resolve at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/request_set.rb:411
                 resolve_current at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems/request_set.rb:423
                  finish_resolve at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems.rb:240
               activate_bin_path at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems.rb:300
                     synchronize at org/jruby/ext/thread/Mutex.java:171
               activate_bin_path at /layers/heroku_ruby/ruby/lib/ruby/stdlib/rubygems.rb:298
                          <main> at /layers/heroku_ruby/bundler/bin/bundle:23
```