Fix print getting started guide
```
heroku/nodejs --buildpack packaged/aarch64-unknown-linux-musl/debug/heroku_ruby --path tmp/ruby-getting-started --pull-policy never
===> ANALYZING
Image with name "my-image" not found
===> DETECTING
======== Results ========
pass: heroku/nodejs@5.1.2
pass: heroku/ruby@12.1.0
Resolving plan... (try #1)
fail: heroku/nodejs@5.1.2 provides unused heroku/nodejs
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 20
```