Fixup tests (#461)
* Use `amd_arm_builder_config` everywhere

Fixes this error locally:

```
## stderr:

Unable to find image 'libcnbtest_qyxgxrypwuai:latest' locally
docker: Error response from daemon: pull access denied for libcnbtest_qyxgxrypwuai, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Run 'docker run --help' for more information

## stdout:



note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_default_app_ubuntu24
```

This happens in this code:

```
        let command_output = context.run_shell_command(
            indoc! {"
                set -euo pipefail
                printenv | sort | grep -vE '(_|^HOME|HOSTNAME|OLDPWD|PWD|SHLVL|SECRET_KEY_BASE)='

                # Output command + output to stdout
                export BASH_XTRACEFD=1; set -o xtrace
                which -a rake
                which -a ruby
            "}
        );
```

Because docker is using the wrong architecture when trying to find the image, but doesn't mention that (very important detail) in the error message.

* Use `app_dir_preprocessor` to modify test files

* # This is a combination of 2 commits.
# This is the 1st commit message:

* Remove unused code

* Remove comments and unused clippy exception

* Update to the latest buildpack tag

* Fix print getting started guide

```
heroku/nodejs --buildpack packaged/aarch64-unknown-linux-musl/debug/heroku_ruby --path tmp/ruby-getting-started --pull-policy never
===> ANALYZING
Image with name "my-image" not found
===> DETECTING
======== Results ========
pass: heroku/nodejs@5.1.2
pass: heroku/ruby@12.1.0
Resolving plan... (try #1)
fail: heroku/nodejs@5.1.2 provides unused heroku/nodejs
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 20
```